"""empty message

Revision ID: 64452910cf18
Revises: 139da90fb855
Create Date: 2018-05-14 15:20:06.474989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64452910cf18'
down_revision = '139da90fb855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forename', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('nhs_number', sa.String(length=10), nullable=True),
    sa.Column('system_number', sa.String(length=10), nullable=True),
    sa.Column('address1', sa.String(length=100), nullable=True),
    sa.Column('address2', sa.String(length=100), nullable=True),
    sa.Column('address3', sa.String(length=100), nullable=True),
    sa.Column('address4', sa.String(length=100), nullable=True),
    sa.Column('address5', sa.String(length=100), nullable=True),
    sa.Column('local_id', sa.String(length=100), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('batch', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch', 'date_created')
    op.drop_table('details')
    # ### end Alembic commands ###
